### ISSUE TITLE
Describtion of the planned work

### ISSUE THREAD

**Issue by FlorianK13** [AlexandraImbrisca/open-MaStR#3]
Hi Alexandra,
could you go to https://github.com/OpenEnergyPlatform/open-MaStR/issues/546 and describe your planned steps there. That would be great to keep the other developer of open-mastr in the loop :)

**Comment by AlexandraImbrisca** [comment]
Hi Florian! Sorry I somehow missed this thread before 🙈  I can and will definitely do that! :) If it helps I can update the issue along the way? e.g., update the status or link the PRs once done

**Comment by FlorianK13** [comment]
Sounds good to me :)
